spring:
  application:
    name: base-service
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
    zookeeper:
      connect-string: 192.168.33.10:2181
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.36.34:3306/base_info?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 122733
#eureka.instance.hostname=192.168.137.1
#
## 默认情况下，Eureka 使用 hostname 进行服务注册，以及服务信息的显示，如需改为ip则配置为true
#eureka.instance.prefer-ip-address=true
## 指定此实例的ip
#eureka.instance.ip-address=192.168.137.1
## 注册中心服务列表中的instanceId，spring.cloud.client.ipAddress该配置为spring cloud自动识别本机网卡ip，
## 多网卡时有可能存在问题，可以通过eureka.instance.ip-address手动指定本机ip
#eureka.instance.instance-id=${eureka.instance.ip-address}:${server.port}
## 讲服务注册到注册中心,默认true
#eureka.client.register-with-eureka=true
## 表示是否从Eureka Server获取注册信息，默认为true。 如果这是一个单点的服务，不需要同步其他节点的数据，可以设为false。
#eureka.client.fetch-registry=true
## 注册中心地址，多个逗号隔开
#eureka.client.serviceUrl.defaultZone=http://192.168.137.1:1001/eureka/
server:
  port: 2003
logging:
  level:
    com:
      xdja: debug

mybatis-plus:
  mapper-locations: classpath:com/xdja/bdp/base/mapping/*.xml
  type-aliases-package: com.xdja.bdp.base.domain

