server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XiaobingYue/config-center
          username: yuexiaobing_haut@163.com
          password: y1227334099
          default-label: master
          search-paths: config